### ISSUE TITLE
请问怎么获取TOken,时效多久啊

### ISSUE THREAD

**Issue by ZAIDU-Miren** [xiaoxiunique/x-kit#1]

**Comment by xiaoxiunique** [comment]
<img width="526" alt="image" src="https://github.com/user-attachments/assets/5902dab3-4044-407e-999a-5fd10331b99b" />

cookie 里面有一个 auth_token 字段

**时效**
只要不要去主要退出，和通过账号密码这些方式在其他地方重新登录，这个 token 就不会失效

**Comment by ZAIDU-Miren** [comment]
> <img alt="image" width="526" src="https://private-user-images.githubusercontent.com/27221739/398858197-5902dab3-4044-407e-999a-5fd10331b99b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNzgzNjgsIm5iZiI6MTczNTI3ODA2OCwicGF0aCI6Ii8yNzIyMTczOS8zOTg4NTgxOTctNTkwMmRhYjMtNDA0NC00MDdlLTk5OWEtNWZkMTAzMzFiOTliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDA1NDEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmODhkYjFmODM0N2Q2OTdlMGVmNDJkM2QxNmE3OTJkYzdjODIxZmIyM2RjM2RlZDJlZTc0MGE0NjU0ZjBkYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.z-l-2hDsReAeRZFB6YnKTh_UOY3Fl9lcC3ZNoZ6ubH8">
> cookie 里面有一个 auth_token 字段
> 
> **时效** 只要不要去主要退出，和通过账号密码这些方式在其他地方重新登录，这个 token 就不会失效

两个token都是一个吗

**Comment by ZAIDU-Miren** [comment]
AUTH_TOKEN=你的X认证Token
GET_ID_X_TOKEN=用于获取用户ID的Token

**Comment by xiaoxiunique** [comment]
你可以使用同一个，我的场景是 GET_ID_X_TOKEN 我用的是一个买的 twitter 账号，这个会好不能关注好友，但是可以调用接口，这个是我为了减少主要的那个账号情况设置的，正常情况用同一个也可以

**Comment by ZAIDU-Miren** [comment]
懂了，start了，我试试

**Comment by ZAIDU-Miren** [comment]
> 你可以使用同一个，我的场景是 GET_ID_X_TOKEN 我用的是一个买的 twitter 账号，这个号好不能关注好友，但是可以调用接口，这个是我为了减少主要的那个账号接口调用设置的，相当于分出一部分接口请求到另外一个账号上面，正常情况用同一个也可以

发现个问题，我添加了一个关注的用户，但是获取的信息是所有的，并不是只针对这个用户的，是预期内的嘛？
![image](https://github.com/user-attachments/assets/982b157d-6cc5-4a2e-86df-8c6dfc03cc9a)

![image](https://github.com/user-attachments/assets/1e140cc9-d1df-4364-a0da-b67721df6dd8)

**Comment by xiaoxiunique** [comment]
会采集这个账号下面的所有关注账号的信息，不是只有这一个用户的，如果你只想做一个用户的，那么可以用一个新的账号，只关注这一个用户就可以了
