### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by Ariken2002** [xiaoxiunique/x-kit#2]
运行时报错：
bun run scripts/fetch-tweets.ts
UNABLE_TO_GET_ISSUER_CERT: unable to get issuer certificate

UNABLE_TO_GET_ISSUER_CERT: unable to get issuer certificate
 path: "https://x.com/manifest.json"

Bun v1.1.42 (Windows x64)

我电脑开了代理，不开代理访问不了X，但一直运行不了，报这个错

**Comment by xiaoxiunique** [comment]
就是代理问题，确定脚本能走代理，打开 TUN mode，浏览器能直接访问 X 不一定 terminal 可以访问
